version: '3'

services:
  chatshare:
    image: ghcr.io/h88782481/chat-share:latest
    container_name: chat-share
    restart: unless-stopped
    ports:
      - '5100:5100'
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - SECRET_KEY=568892D12C2923D
      - AUTHORIZATION=568892D12C2923D
      - DOMAIN_CHATGPT=https://chatshare.sfo1.zeabur.app

